### ISSUE TITLE
Provided Tacotron2 encoder can suddenly interrupts in the middle of a sentence

### ISSUE THREAD

**Issue by ksofiyuk** [mozilla/TTS#521] opened 2020-09-18 10:41 UTC
Hi,
I noticed that the encoder doesn't work properly on some sentences. It can interrupts in the middle of a sentence. Here is an example of such sentence:

> It was a miracle, how much ease with wildness was managed in such a small space.

The encoder produces spectrogram only for "It was a miracle" part of the sentence and then interrupts. However, if you remove the comma, it will encode the whole sentence.

I reproduced this bug with the notebook [DDC_TTS_and_MultiBand_MelGAN_Example.ipynb](https://github.com/mozilla/TTS/blob/master/notebooks/DDC_TTS_and_MultiBand_MelGAN_Example.ipynb) from current master.

**Comment by erogol** [comment] 2020-09-18 11:09
It is not a bug just false model behavior.
It is not a production-grade model since the dataset is not great. Therefore it is expectable to have such false modes.

Training the model more would make it better or replacing stopnet with a constant check of attention end would solve it (if you know the internals of the model).

**Comment by erogol** [comment] 2020-09-18 11:10
Since it is not a bug I close this but feel free to continue it on discourse.

**Closed by erogol** 2020-09-18 11:10 UTC

**Comment by ksofiyuk** [comment] 2020-09-18 11:36
Thank you for the clarification.
Of course, I understand that it is related to a model behavior. But for me there seemed to be some quite obvious bug in model design, because this incorrect behavior happens rather often on my text corpa (around 1% of sentences interrupts earlier than it needed).

P.S. I use this TTS for my personal purposes as is, not for research. My main field of interests lays in computer vision. So I didn't dive into the internals of the model.
